using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LPToolKit.Implants;
using LPToolKit.MIDI;
using LPToolKit.MIDI.Hardware;

namespace LPToolKit.Core.Tasks
{
    /// <summary>
    /// This is an event generated by an Implant in response to an
    /// ImplantEvent to achieve some goal.
    /// </summary>
    public class ImplantAction : IKernelTask
    {       
        #region Properties

        /// <summary>
        /// The implant this action came from.
        /// </summary>
        public Implant Source;

        #endregion

        #region IKernalTask Implementation

        public virtual void RunTask()
        {
            throw new NotImplementedException();
        }

        public virtual int ExpectedLatencyMsec
        {
            get { return 500; }
        }

        /// <summary>
        /// Adds this task to the scheduler.
        /// </summary>
        public virtual IKernelTask ScheduleTask()
        {
            Kernel.Current.Add(this);
            return this;
        }

        #endregion
    }

}
